-- Folders table
create table if not exists folders (
  id bigint primary key generated by default as identity,
  name varchar(255) not null,
  parent_id bigint references folders(id),
  is_root boolean default false not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Diagrams table
create table if not exists diagrams (
  id bigint primary key generated by default as identity,
  content text not null,
  last_updated timestamp with time zone default timezone('utc'::text, now()) not null,
  name varchar(255),
  folder_id bigint not null references folders(id)
);

-- Create root folder if it doesn't exist
insert into folders (name, parent_id, is_root)
select 'Root', null, true
where not exists (select 1 from folders where is_root = true);
